version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "MyTopic:1:1"  # Adjust topic name and partitions/replication factors as needed

  # producer:
  #   build: 
  #     context: ./Producer
  #     dockerfile: Producer.Dockerfile
  #   environment:
  #     KAFKA_TOPIC: "my-topic"  # Adjust topic name as needed
  #     KAFKA_SERVER: "kafka:2024"
  #     INPUT_FILE: "/app/data/input.txt"  # Adjust input file path as needed
  #   volumes:
  #     - ./data:/app/data  # Mount directory containing input file

  # consumer:
  #   build:
  #     context: ./Consumer
  #     dockerfile: Consumer.Dockerfile
  #   environment:
  #     KAFKA_TOPIC: "my-topic"  # Adjust topic name as needed
  #     KAFKA_SERVER: "kafka:2024"
  #     KAFKA_CONSUMER_GROUP: "my-consumer-group"  # Adjust consumer group name as needed
